### ISSUE TITLE
feat: specify directory for `idb` sqlite files

### ISSUE THREAD

**Issue by TillaTheHun0** [aaronhuggins/pouchdb_deno#7] opened 2022-04-19 18:42 UTC
Maybe I missed how to do this, but I would like to be able to specify the directory used to store the `sqlite` files created when using the `idb` adapter. Seems like current functionality only allows the `cwd`?

On a hunch, I took a shot at just using `prefix` like what is described in [Pouch docs](https://pouchdb.com/api.html#defaults) with respect to LevelDB, but the result is the `sqlite` file name is prefixed:
```js
// results in a file in cwd named D__pouch_^12fpath^12fto^12ffilefoobar.sqlite
new PouchDB.defaults({ adapter: 'idb', prefix: '/path/to/file'})("foobar")
```

My use case is that I would like to be able to place the files into a directory, that the Deno task has permissions to write to ie.
`deno run --allow-write=/tmp/foo --allow-read=/tmp/foo foo.js`

Thanks!

**Comment by aaronhuggins** [comment] 2022-04-19 19:20
Hmm, yes, the prefix is getting passed raw to the Pouch `idb` adapter, which then instantiates an IndexedDB database with that name, resulting in your behavior. This is expected behavior for the adapter.

There's a few layers here. PouchDB `idb` <= [aaronhuggins/indexeddb](https://github.com/aaronhuggins/indexeddb) <= [aaronhuggins/websql](https://github.com/aaronhuggins/websql)

The WebSQL adapter exposes a module-global `configureSQLiteDB` method, which is used for setting some lower-level SQLite options.

I think I can add an API to the WebSQL configuration routine to allow a root dir globally for reading/writing all sqlite DBs. If this routine was called before instantiating Pouch, I think it would work.

What do you think of this idea?

**Comment by TillaTheHun0** [comment] 2022-04-19 19:28
> There's a few layers here. PouchDB idb <= [aaronhuggins/indexeddb](https://github.com/aaronhuggins/indexeddb) <= [aaronhuggins/websql](https://github.com/aaronhuggins/websql)

Yea, I started to dig into it, but was hopping down the rabbit hole and figured i'd ask if I was missing something. 😅 

So with your idea, what would the usage of this PouchDB module look like,  when wanting to satisfy the use case above? Would calling `configureSQLiteDB` be handled internally within this module and exposed via current api for `prefix`? or would consumers of this module need to separately call `configureSQLiteDB`?

I guess it comes down to the api, really. Apologies if I misunderstand.

**Comment by aaronhuggins** [comment] 2022-04-19 21:43
No, you understood perfectly. I'm going to investigate both questions you raised.

I have an idea for intercepting the IndexedDB create call for the `idb` adapter to hijack the prefix flag... would make it fairly ergonomic.

**Comment by aaronhuggins** [comment] 2022-04-20 02:54
I figured out what needs to be done. I'm making a note here on the issue for my own use, I don't have a way for this to work for your case yet.

1. Override `escapeDatabaseName` in IndexedDB implementation to allow pass-through of valid file path separators
2. In the `idb` adapter export, wrap the export in a function; detect Deno and apply `PouchDB.adapters.idb.use_prefix = false` to avoid naming with `_pouch_` internal prefix

@TillaTheHun0 Once I apply those two fixes (one in a dependency), then you should be able to supply your own custom prefix like you expect and it will store the DBs in a path instead of cwd.

**Comment by TillaTheHun0** [comment] 2022-04-20 13:13
> hijack the prefix flag... would make it fairly ergonomic.

I think using the `prefix` flag would be ideal from a usage standpoint.

It sounds like you have an idea of what would have to be done. Let me know how I could help.

**Comment by aaronhuggins** [comment] 2022-04-20 21:32
I need to do a little code cleanup and add some docs to the README, but hey! it works.

**foobar.ts**
```typescript
// File: foobar.ts
import PouchDB from "https://raw.githubusercontent.com/aaronhuggins/pouchdb_deno/5336ce7d3143460078bd2fd7164a7528447ea8bd/modules/pouchdb/mod.ts"

const PouchFactory = PouchDB.defaults({
  adapter: "idb",
  prefix: "./path/to/file/",
  systemPath: "./path/to/system/"
})
new PouchFactory("foobar")
```

**command**
```shell
deno run --allow-write=./path/to/file,./path/to/system --allow-read=./path/to/file,./path/to/system foobar.ts
```

You can try it out by using the raw Github import in the above example. I'll ping back when release is published to Denoland, and close the issue.

Please monkey and try to break it. Let me know what you find.

**Comment by TillaTheHun0** [comment] 2022-04-20 21:57
@aaronhuggins awesome work! I'll try it out soon and let you know if anything comes up. What's the distinction between `prefix` and `systemPath`?

**Comment by aaronhuggins** [comment] 2022-04-20 22:05
> @aaronhuggins awesome work! I'll try it out soon and let you know if anything comes up. What's the distinction between `prefix` and `systemPath`?

https://github.com/aaronhuggins/pouchdb_deno/blob/5336ce7d3143460078bd2fd7164a7528447ea8bd/modules/pouchdb_types/pouchdb.ts#L1091

**Comment by aaronhuggins** [comment] 2022-04-20 23:43
Also added something to the [README](https://github.com/aaronhuggins/pouchdb_deno/tree/886aaf7288493369763b164f5c77885585eb5ce0#indexeddb).

**Comment by aaronhuggins** [comment] 2022-04-21 14:22
Yeah, PouchDB docs don't explicitly address this for LevelDB, but I think the trailing slash is required there, too. Easy enough to fix, since I'm already intercepting the options with my workaround.

**Comment by TillaTheHun0** [comment] 2022-04-21 14:25
> but I think the trailing slash is required [for LevelDB], too

@aaronhuggins _if_ the trailing slash is required for LevelDB, it might be a good idea to also require it here (which your change already does), and then just document that. So there is feature parity between the two.

**Comment by aaronhuggins** [comment] 2022-04-21 14:26
*sigh* making me pull out node, LOL.

You're right, though.

**Comment by TillaTheHun0** [comment] 2022-04-21 14:28
I sympathize with that feeling 😆 . But hey, LevelDB docs reuse, and potentially less custom code to maintain, right?

**Comment by aaronhuggins** [comment] 2022-04-21 14:39
Yep. trailing slash required.

**foobar.js**
```javascript
const PouchDB = require('pouchdb-core');
const leveldb = require('pouchdb-adapter-leveldb');
const fs = require('fs');

fs.mkdirSync('./level/db', { recursive: true });

PouchDB.plugin(leveldb);

const db = new PouchDB('test', { adapter: 'leveldb', prefix: './level/db' });

db.post({ hello: 'world' }).then(console.log, console.error);
```

**output**
```shell
> ls -l ./level
total 8
drwxrwxr-x 2 ahuggins ahuggins 4096 Apr 21 09:36 db
drwxr-xr-x 2 ahuggins ahuggins 4096 Apr 21 09:36 dbtest
```

**Comment by TillaTheHun0** [comment] 2022-04-21 14:44
Cool, thanks for confirming that. Then I think documenting that the trailing slash is required (just like with `prefix` in LevelDB) is the solution.

**Comment by TillaTheHun0** [comment] 2022-04-21 14:57
With e24f17e96ad3c2322be971b5a820e7b0f0bf2432, this issue seems done. Thanks for all your work on this! Idk if you had more work in mind, but please feel free to close this issue. I can ref that commit to get what I need for now. Thanks!

**Comment by aaronhuggins** [comment] 2022-04-21 15:04
Released as https://deno.land/x/pouchdb_deno@v2.0.0-PouchDB+7.2.2

**Closed by aaronhuggins** 2022-04-21 15:04 UTC
Labels: enhancement
